Tarasenko Nikita and Tanashkin Valeriy
h31/NetworksLab2021 pull request #11
Opened 2021-10-07 16:20 UTC by GetRhymes

In this PR we want to present Client (dir TKSClient), Server(dir TKSServer) and Util Lib (dir PolySerialize)

2021-10-08 10:32 UTC, nikitarasenko commented
https://github.com/GetRhymes/PolySerialize

https://github.com/GetRhymes/TKSClient

https://github.com/GetRhymes/TKSServer

2021-10-09 11:04 UTC, h31 requested changes

2021-10-09 11:04 UTC, h31 commented on PolySerialize/src/main/java/com/poly/models/Message.java
> +public class Message implements Serializable {
Зачем?

2021-10-09 11:04 UTC, h31 commented on PolySerialize/src/main/java/com/poly/sockets/MessageReader.java
> +        for (int i = 0; i < 4; i++) {
DataInputStream

2021-10-09 11:04 UTC, h31 commented on PolySerialize/src/main/java/com/poly/sockets/MessageWriter.java
> +            outputStream.write(strMessage.getBytes().length / (int) Math.pow(2, 24));
Сдвиг

2021-10-09 11:04 UTC, h31 commented on TKSClient/src/main/java/com/poly/client/MessageData.kt
> +        if (message.matches(Regex("""(\s+|)"""))) return null
???

2021-10-09 11:04 UTC, h31 commented on TKSClient/src/main/java/com/poly/client/Client.kt
> +            sleep(1)
!!!

2021-10-09 11:04 UTC, h31 commented on TKSServer/src/main/java/com/poly/server/threads/ClientThread.java
> +                            message.getMessage().setDate((LocalDate.now().toString() + " " + LocalTime.now().toString()).replace(":", "."));
replace?

2021-10-09 11:04 UTC, h31 commented on TKSServer/src/main/java/com/poly/server/threads/ClientThread.java
> +                        message = null;
?

2021-10-09 11:04 UTC, h31 commented on TKSClient/src/test/java/MessageDataTest.kt
> +        val file = File("${System.getProperty(USER_HOME)}${File.separator}test.txt")
Junit TemporaryDir

2021-10-09 11:04 UTC, h31 commented on PolySerialize/src/main/java/com/poly/sockets/MessageReader.java
> +        message.parseToMessage(StringUtils.newStringUtf8(msg));
?

2021-10-09 11:04 UTC, h31 commented on TKSServer/src/main/java/com/poly/server/threads/ClientThread.java
> +                    e.printStackTrace();
close?

2021-10-14 18:00 UTC, NastyPill commented on PolySerialize/src/main/java/com/poly/models/Message.java
> +public class Message implements Serializable {
- [x] убрать

2021-10-14 18:01 UTC, NastyPill commented on PolySerialize/src/main/java/com/poly/sockets/MessageReader.java
> +        for (int i = 0; i < 4; i++) {
Обсудили, вроде бы, Вы сказали, что это больше рекомендация, + тут как раз он и используется ( в начале класса объявлен)

2021-10-14 18:01 UTC, NastyPill commented on PolySerialize/src/main/java/com/poly/sockets/MessageWriter.java
> +            outputStream.write(strMessage.getBytes().length / (int) Math.pow(2, 24));
- [x] Сдвиг

2021-10-14 18:02 UTC, NastyPill commented on TKSClient/src/main/java/com/poly/client/MessageData.kt
> +        if (message.matches(Regex("""(\s+|)"""))) return null
- [x] Убрать и решить проблему с отсылкой сообщений вида : "\s+"

2021-10-14 18:02 UTC, NastyPill commented on TKSClient/src/main/java/com/poly/client/Client.kt
> +            sleep(1)
- [ ] Разобраться  со слипом

2021-10-14 18:03 UTC, NastyPill commented on TKSServer/src/main/java/com/poly/server/threads/ClientThread.java
> +                            message.getMessage().setDate((LocalDate.now().toString() + " " + LocalTime.now().toString()).replace(":", "."));
Обсудили, нужно добавить данный специфичный формат пересылки даты в документацию по протоколу

2021-10-14 18:05 UTC, NastyPill commented on TKSServer/src/main/java/com/poly/server/threads/ClientThread.java
> +                        message = null;
- [x] Убрать  + переписать логику с ифками более лаконично

2021-10-14 18:06 UTC, NastyPill commented on TKSClient/src/test/java/MessageDataTest.kt
> +        val file = File("${System.getProperty(USER_HOME)}${File.separator}test.txt")
Обсудили, вроде бы это была рекомендация, т.к. в данном тесте файл удаляется

2021-10-14 18:08 UTC, NastyPill commented on PolySerialize/src/main/java/com/poly/sockets/MessageReader.java
> +        message.parseToMessage(StringUtils.newStringUtf8(msg));
Обсудили, решили не менять

2021-10-14 18:08 UTC, NastyPill commented on TKSServer/src/main/java/com/poly/server/threads/ClientThread.java
> +                    e.printStackTrace();
- [ ] привести блоки try-catch к нормальному виду

2021-10-16 12:04 UTC, h31 approved these changes

2021-10-22 18:47 UTC, closed without merging