[Leonid Khvatskin, 3530901/80203] Lab 2
h31/NetworksLab2021 pull request #13
Opened 2021-10-16 07:02 UTC by TheGreenBeaver

2021-11-04 20:30 UTC, h31 requested changes

2021-11-04 20:30 UTC, h31 commented on index.js
> +// // const Message = require('./common-classes');
Почистите код от закомментированных строчек. Если понадобится история изменений, она есть в Гите.

2021-11-04 20:30 UTC, h31 commented on client/index.js
> +  const logDir = path.join(
FYI: Логи - это очень хорошо, в серьёзных проектах помните про их ротацию.

2021-11-04 20:30 UTC, h31 commented on common-classes/message.js
> +  static #parseBunch(payload, startOffset, count, parser) {
`Bunch`?

2021-11-04 20:30 UTC, h31 commented on common-classes/generic-dns-accessor.js
> +  static async #requestDatabaseConnection(requestedDatabase, mark) {
Так и не смог понять, для чего здесь используется Redis

2021-11-04 22:50 UTC, Leonid-Khvatskin commented on common-classes/message.js
> +  static #parseBunch(payload, startOffset, count, parser) {
да, Bunch... Распарсить **пачку** записей - ведь в каждой секции их может быть несколько

2021-11-04 22:53 UTC, Leonid-Khvatskin commented on common-classes/generic-dns-accessor.js
> +  static async #requestDatabaseConnection(requestedDatabase, mark) {
На сервере - в качестве непосредственно базы данных (к ней обращаемся с тем, чтобы вычислить ответ на запрос), на клиенте - для кэширования. Правда, Вашему комменту 2 часа - на тот момент, кажется, и правда трудно было по коду понять, зачем здесь редис... Работа ещё очень в большой степени **In progress**)

2021-11-04 22:54 UTC, Leonid-Khvatskin commented on index.js
> +// // const Message = require('./common-classes');
Уже убрал
Работал над другими файлами, вообще не заметил, что тут полфайла в комментах

2021-12-22 20:56 UTC, h31 approved these changes

2021-12-22 20:56 UTC, closed without merging