Lab1, Цаплин Илья 3530901/80203
h31/NetworksLab2021 pull request #20
Opened 2021-10-23 09:21 UTC by TsaplinIA

Лабораторная работа №1

2021-10-23 10:15 UTC, h31 commented
На сервере работает

2021-11-04 18:50 UTC, h31 requested changes

2021-11-04 18:50 UTC, h31 commented on server/server.py
> +import struct
Почистите код

2021-11-04 18:50 UTC, h31 commented on server/ThreadForClient.py
> +            size -= msg_tmp.__len__()
Почему `__len__`, а не просто `len`?

2021-11-04 18:50 UTC, h31 commented on server/ThreadForClient.py
> +    def saveRecv(self, size: int):
`save`?

2021-11-04 18:50 UTC, h31 commented on server/ThreadForClient.py
> +            # print("flag set")
Почистите файлы от закомментированного кода. Если вам понадобятся предыдущие версии кода, их можно найти в Гите.

2021-11-04 18:50 UTC, h31 commented on server/ThreadForClient.py
> +            f = open(actual_path, "w+b")
Зачем сохранять файл на диске?

2021-11-04 18:50 UTC, h31 commented on Lab1.md
> +1. От клиента к серверу ![ClientToServer](.\images\ClientToServer.png)
Сделайте, пожалуйста, чтобы картинки отображались на Гитхабе. У меня на компьютере с Unix-подобной системой картинки тоже не отображаются.

2021-11-04 18:50 UTC, h31 commented on client/client.py
> +sock.connect(('networkslab-ivt.ftp.sh', 9090))
Как можно сделать так, чтобы адрес сервера не был жестко зашит в код?

2021-11-04 18:50 UTC, h31 commented on client/client.py
> +def getNonExistentName(file_name):
Функция дублируется в другом файле. Устраните дублирование.

2021-11-27 11:11 UTC, TsaplinIA commented on client/client.py
> +sock.connect(('networkslab-ivt.ftp.sh', 9090))
Это можно сделать, передавая адрес сервера как аргумент при запуске клиента. Все остальные замечания исправил в свежем коммите.

2021-12-03 19:14 UTC, h31 approved these changes

2021-12-17 00:35 UTC, closed without merging