Lab1, Шрамков Максим
h31/NetworksLab2021 pull request #21
Opened 2021-10-28 16:04 UTC by k1unk

2021-11-05 10:36 UTC, h31 commented
Проверил. К сожалению, Гитхаб не позволяет писать комментарии для подмодулей

2021-12-03 19:32 UTC, h31 requested changes

2021-12-03 19:32 UTC, h31 commented on client/Client.java
> +        Socket socket = new Socket("localhost", 5111);
Можно ли сделать так, чтобы пользователь мог указать адрес сервера без того, чтобы менять строки в программе?

2021-12-03 19:32 UTC, h31 commented on server/ClientThread.java
> +                long time = Instant.now().toEpochMilli();
Этот код нужно выполнять только тогда, когда не получилось считать длину?

2021-12-03 19:32 UTC, h31 commented on server/ClientThread.java
> +                String serverDate = Long.toString(time);
Этот код повторяется в программе два раза, можно ли что-нибудь с этим сделать?

2021-12-03 19:32 UTC, h31 commented on server/ClientThread.java
> +                text = reader.readUTF();
Посмотрите, как работает метод `readUTF`. Если программа на другом языке (например, Python) пришлёт вам строку, сможет ли этот метод считать её? Стоит ли описать подобное поведение в описании протокола?

2021-12-03 19:32 UTC, h31 commented on server/ClientThread.java
> +            if (command == 'g') {
Enum?

2021-12-03 19:32 UTC, h31 commented on server/Parser.java
> +                if (bytes[ind + 1] == '\\') {
Не увидел в описании протокола, зачем вы это делаете

2021-12-03 19:32 UTC, h31 commented on server/Parser.java
> +        while (true) {
Очень похожий код, который повторяется много-много раз. Можно ли что-нибудь с этим сделать?

2021-12-03 19:32 UTC, h31 commented on server/Server.java
> +        for (int i = 0; i < sockets.size(); i++) {
for each?

2021-12-03 19:32 UTC, h31 commented on server/Server.java
> +        ArrayList<Socket> sockets = new ArrayList<>();
Почему у переменной тип `ArrayList`? Почему нам нужен именно `ArrayList`, а не любой другой список или коллекция?

2021-12-09 22:39 UTC, k1unk commented on client/Client.java
> +        Socket socket = new Socket("localhost", 5111);
Все замечания исправил

2021-12-18 13:00 UTC, h31 approved these changes

2021-12-20 19:00 UTC, closed without merging