Lab2[Курняков Пётр, Невоструева Яна]
h31/NetworksLab2021 pull request #22
Opened 2021-11-03 16:03 UTC by pupptmstr

2021-11-04 19:55 UTC, h31 requested changes

2021-11-04 19:55 UTC, h31 commented on lab2/src/main/kotlin/com/monkeys/ntp/Utils.kt
> +fun parseArguments(args: List<String>): WorkType = when {
Выглядит достаточно аккуратно и понятно, но смотрели ли в сторону библиотек для парсинга аргументов?

2021-11-04 19:55 UTC, h31 commented on lab2/src/main/kotlin/com/monkeys/ntp/Main.kt
> +                println("Incorrect arguments or it is impossible to establish a connection with the specified server.\n" +
Насколько вы в этом месте программы способны гарантировать, что исключение возникло именно из-за проблем с подключением?

2021-11-04 19:55 UTC, h31 commented on lab2/src/main/kotlin/com/monkeys/ntp/client/Client.kt
> +                val packet = DatagramPacket(ntpPacket, ntpPacket.size, InetAddress.getByName(host ?: "pool.ntp.org"), port ?: NTP_PORT)
Мелочь, но я посоветовал вместо `?:` использовал дефолтные значения аргументов в конструкторе, или даже перенести этот код в `Main`, чтобы разделить непосредственно логику протокола и обвязку для запуска.

2021-11-04 19:55 UTC, h31 commented on lab2/src/main/kotlin/com/monkeys/ntp/client/Client.kt
> +                val response = DatagramPacket(ntpPacket, ntpPacket.size)
Можно перенести поближе к месту использования

2021-11-04 19:55 UTC, h31 commented on lab2/src/main/kotlin/com/monkeys/ntp/models/NtpPacket.kt
> +    private fun convertTo32(array: ByteArray, offset: Int): Long {
Нет ли библиотечных функций для этой задачи?

2021-11-04 19:55 UTC, h31 commented on lab2/src/main/kotlin/com/monkeys/ntp/Utils.kt
> +        processBuilder.command("bash", "-c", "ip a | grep inet | grep -v inet6 | grep -v 127.0.0.1 | awk '{print \$2}'")
Что вы хотите сделать этой командой? Какие данные ожидаете получить? Как это будет работать, если в системе нет утилиты `ip`? Как будет работать, если у компьютера несколько интерфейсов?

2021-11-05 08:30 UTC, NevostruevaYana commented on lab2/src/main/kotlin/com/monkeys/ntp/client/Client.kt
> +                val response = DatagramPacket(ntpPacket, ntpPacket.size)
исправлено
отправляющаяся дейтаграмма создается перед отправкой, принимающаяся перед получением

2021-11-05 08:38 UTC, pupptmstr commented on lab2/src/main/kotlin/com/monkeys/ntp/Utils.kt
> +        processBuilder.command("bash", "-c", "ip a | grep inet | grep -v inet6 | grep -v 127.0.0.1 | awk '{print \$2}'")
Предпологается, что сервер запускается на linux-машине. Утилита ip - стандартная и есть в любом linux дистрибутиве (в отличие от той же ifconfig).

2021-11-05 08:41 UTC, pupptmstr commented on lab2/src/main/kotlin/com/monkeys/ntp/models/NtpPacket.kt
> +    private fun convertTo32(array: ByteArray, offset: Int): Long {
Учитывая особенности - нет. По факту это простая работа с байтами, библиотечных функций для этого нет, а те что есть преобразуют байты в доп. код, что нам не нужно

2021-11-05 08:46 UTC, pupptmstr commented on lab2/src/main/kotlin/com/monkeys/ntp/Utils.kt
> +fun parseArguments(args: List<String>): WorkType = when {
Для этого нет особого смысла, ибо аргументов не так много. К тому же эту часть кода мы взяли из предыдущего залания (сам выбор клиента или сервера). Мы уверены, что она нормально работает (плюс была проверена вами в прошлый раз)

2021-11-05 08:46 UTC, NevostruevaYana commented on lab2/src/main/kotlin/com/monkeys/ntp/client/Client.kt
> +                val packet = DatagramPacket(ntpPacket, ntpPacket.size, InetAddress.getByName(host ?: "pool.ntp.org"), port ?: NTP_PORT)
Вся логика для этого уже была реализована, убрали ?: , все прекрасно работает

2021-11-05 09:53 UTC, NevostruevaYana commented on lab2/src/main/kotlin/com/monkeys/ntp/Main.kt
> +                println("Incorrect arguments or it is impossible to establish a connection with the specified server.\n" +
Полностью убрали блок try-catch, так как всю обработку производит функция парсинга и подключение происходит в любом случае
если введены неверные хост или порт ошибка появляется уже на этапе создания дейтаграммы, если же хост и пост указаны верны, например localhost:4445 (подключение к нашему серверу), а сервер в это время не включен, дейтаграмма отсылается, но ответ не приходит (что логично). Для этого также добавили таймаут ожидания и если не получаем ответ в течение какого-то времени также выкидываем ошибку и предупреждаем пользователя

2021-12-01 16:46 UTC, closed without merging