Джеус Андрей, №3530901/80203
h31/NetworksLab2021 pull request #23
Opened 2021-11-04 13:57 UTC by MickeyMouseMouse

2021-11-05 12:20 UTC, h31 requested changes

2021-11-05 12:20 UTC, h31 commented on lab2/TFTP_Server.py
> +		clients[address[0]][address[1]] = None
Tuple?

2021-11-05 12:20 UTC, h31 commented on lab2/PackageHandler.py
> +        delay = 0.1
Можно ли без `delay`?

2021-11-05 12:20 UTC, h31 commented on lab2/PackageHandler.py
> +            if self.work_mode == 1: # 1 = GET (download from server)
Direction? Enum?

2021-11-05 12:20 UTC, h31 commented on lab2/PackageHandler.py
> +                        buffer = file.read(512)
А остальные блоки? Почему отдельно?

2021-11-06 00:05 UTC, MickeyMouseMouse commented on lab2/PackageHandler.py
> +        delay = 0.1
Да. Я вообще был вынужден немного переделать структуру приложения, потому что мой прежний вариант не захотел работать со стороним TFTP сервером (я попробовал два разных). В текущем варианте delay отсутствует (его функцию выполняет таймаут сокета).

2021-11-06 00:06 UTC, MickeyMouseMouse commented on lab2/PackageHandler.py
> +            if self.work_mode == 1: # 1 = GET (download from server)
Переделал на enum

2021-11-06 00:10 UTC, MickeyMouseMouse commented on lab2/PackageHandler.py
> +                        buffer = file.read(512)
Здесь все-таки лучше оставить так, иначе код становится еще более запутанным. Дело в том, что на первый запрос клиента (GET или PUT) сервер должен ответить либо первой порцией данных, либо пакетом подтверждения с номером блока 0. Также на первом этапе сервер должен либо открыть требуемый файл на чтение, либо создать новый для записи. Все это нужно сделать всего один раз, поэтому все же не стоит помещать этот код в тело цикла.

2021-11-06 00:13 UTC, MickeyMouseMouse commented on lab2/PackageHandler.py
> +        delay = 0.1
Чтобы код было легче воспринимать, я разделил серверную и клиентскую части по двум разным модулям. Раньше все было свалено в один файл, и из-за этого появлялось лишнее нагромождение.

2021-11-06 00:28 UTC, MickeyMouseMouse commented on lab2/TFTP_Server.py
> +		clients[address[0]][address[1]] = None
Здесь в любом случае нужно сопоставлять ip адрес, номер порта и экземпляр класса обработчика. Будут эти сущности записаны друг за другом в массиве или во вложенном ассоциативном массиве (как сейчас) - абсолютно без разницы (проще не становится, никакой экономии не возникает).

2021-11-13 13:19 UTC, h31 approved these changes

2021-12-02 16:26 UTC, closed without merging