Lab2 - DNS Бедрин/Медведев
h31/NetworksLab2021 pull request #24
Opened 2021-11-04 15:30 UTC by HaveAHeart

DNS с излишне минималистичным описанием.
Потестили работу:
Клиента с нашим сервером, с крупными DNS-серверами (1.1.1.1, 8.8.8.8) для всех 4 типов записей (A/AAAA/TXT/MX)
Сервера с нашим клиентом, с nslookup для всех тех же самых типов записей (set type=a/aaaa/txt/mx)

2021-11-05 12:31 UTC, h31 commented
Показали, как работает, с меня - проверить код

2021-11-23 23:04 UTC, h31 requested changes

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Client.kt
> +        val type: RecordType = when (scanner.nextLine().toUpperCase()) {
FYI: по возможности, используйте аргументы командной строки для задания параметров - такую программу проще использовать для автоматизации, кроме того, если она часто вызывается, не нужно каждый раз вводить одни и те же данные

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Client.kt
> +            exitProcess(1)
Какие проблемы могут возникнуть, если в обработчике исключений завершать программу?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Client.kt
> +                println("answers = $res")
Длинная функция, есть смысл разбить её на несколько

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Main.kt
> +    when (args[0]) {
А что будет, если аргументы не указаны?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Main.kt
> +                    println("Incorrect port format. Used default port: $port")
Какие проблемы могут возникнуть, если программа автоматически заменяет некорректные параметры на корректные, но другие?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Server.kt
> +                is RecordType.A -> RecordType.A().size()
Extension function?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Server.kt
> +            errorFunc(dnsMsg, ResponseCode.of(1))
?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Utils.kt
> +    val qName = ByteArray(inName.length + 2)
Почему ` + 2`?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Utils.kt
> +fun byteSubsequence(array: ByteArray, start: Int, end : Int): ByteBuffer =
Отформатируйте код

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/models/Header.kt
> +            if (headerBytes.size < 12) throw IllegalArgumentException()
Где обрабатывается это исключение?

2021-11-23 23:04 UTC, h31 commented on src/main/kotlin/Server.kt
> +            if (resource.type == RecordType.of(15)) {
Это MX? Если да, то можно ли заменить числовые литералы на что-нибудь, что легче читается (enum, например)?

2021-11-25 16:22 UTC, dVede commented on src/main/kotlin/Client.kt
> +        val type: RecordType = when (scanner.nextLine().toUpperCase()) {
Решили остановиться на данном формате ввода, так как иначе размер команды был очень большой. Лучшем вариантом было сделать подобно nslookup, где тип записи задается перед запросом.

2021-11-25 17:08 UTC, dVede commented on src/main/kotlin/Utils.kt
> +    val qName = ByteArray(inName.length + 2)
inName.length + 2 - это количество октетов для передачи доменного имени. Отличие от изначального представления в начальной метке (так как там нет точки) и в последнем "0" (для определения конца доменного имени). Даже если количество символом больше 9, значение запишется в один октет. Единственное, что стоит проверять дополнительно, так это то, что метка не больше 63, так как первые 2 бита используются для смещения, а соответственно длинна доменна на разных уровнях не может быть больше 63. При возникновении подобной ситуации мы решили обрезать домен до 63.

2021-11-25 17:08 UTC, dVede commented on src/main/kotlin/models/Header.kt
> +            if (headerBytes.size < 12) throw IllegalArgumentException()
Исправлено

2021-11-25 17:26 UTC, dVede commented on src/main/kotlin/Server.kt
> +            if (resource.type == RecordType.of(15)) {
Да, можно заменить. Решили заменить на строковые переменные.

2021-11-25 17:30 UTC, dVede commented on src/main/kotlin/Main.kt
> +    when (args[0]) {
Исправлено

2021-11-25 17:31 UTC, dVede commented on src/main/kotlin/Client.kt
> +                println("answers = $res")
Исправлено. Вывод результата вынесен в отдельную функцию.

2021-11-25 17:54 UTC, dVede commented on src/main/kotlin/Client.kt
> +            exitProcess(1)
Никаких мыслей на ум не пришло, поэтому просто произвели замену exitProcess(1) на return.

2021-11-25 22:53 UTC, dVede commented on src/main/kotlin/Client.kt
> +            exitProcess(1)
В контексте блока try/catch, если не ошибаюсь, то блок finally не выполнится после вызова exitProcess().

2021-11-26 10:41 UTC, HaveAHeart commented on src/main/kotlin/Server.kt
> +            errorFunc(dnsMsg, ResponseCode.of(1))
Проверяем входящий пакет по флагам на корректность - он:
должен быть запросом (flags.qr = True)
не должен иметь выставленный бит Authoritative Answer (он выставляется только в ответе)
не должен быть truncated (пока не работаем с truncated запросами)
z всегда должен быть равен 0 ([rfc](https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.1))
rcode должен быть равен 0 (меняем его только при ответе)
запрос должен содержать хотя бы 1 question

Если что-то из этого не так, то мы вешаем rcode = 1 - некорректный запрос ([rfc](https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.1), page 26)

2021-11-26 12:43 UTC, HaveAHeart commented on src/main/kotlin/Main.kt
> +                    println("Incorrect port format. Used default port: $port")
попытки открыть порт, который, возможно, занят.
В целом - поведение, которое не соответствует тому, что от программы ждёт пользователь - плохо, поэтому теперь просто заканчиваем работу.

2021-11-26 12:44 UTC, HaveAHeart commented on src/main/kotlin/Utils.kt
> +fun byteSubsequence(array: ByteArray, start: Int, end : Int): ByteBuffer =
fixed

2021-11-27 10:45 UTC, HaveAHeart commented on src/main/kotlin/Server.kt
> +                is RecordType.A -> RecordType.A().size()
поправили имеющие статический размер (A/AAAA)

2021-11-27 11:01 UTC, h31 approved these changes

2021-12-02 16:27 UTC, closed without merging