Lab1
h31/NetworksLab2021 pull request #25
Opened 2021-11-05 18:45 UTC by astudina

2021-11-17 11:15 UTC, astudina commented
Список исправлений:
- Попробовали запускать клиентов с разных компьютеров, нашли ошибку. Скорректировали отправку вложений (теперь вложения сохраняются в ту папку, в которой запускается клиент) 
- Сделали так, что теперь клиент не может выбрать имя "Server", так как оно служебное. Также теперь все сообщения от сервера выделяются другим цветом.
- Обработали отключение клиента при закрытии консоли
- Скорректировали обработку имени файла с несколькими точками
- Скорректировали название некоторых модулей и переменных, чтобы они были более информативными
- Добавили название ошибки при обработке отключения сервера
- Скорректировали описание протокола

2021-11-20 08:11 UTC, h31 requested changes

2021-11-20 08:11 UTC, h31 commented on lab1/clientThread.py
> +            # except ConnectionResetError:
Уберите, пожалуйста, закомментированный код

2021-11-20 08:11 UTC, h31 commented on lab1/lab1.md
> +    - Изначально отправляются два сообщения: размер последующего сообщения и само сообщение, включающее флаг о наличии/
Как именно у вас указывается размер?

2021-11-20 08:11 UTC, h31 commented on lab1/client.py
> +        message_parts = message.split(' & ')
Как будет работать этот код, если в сообщении несколько символов ` & `? Например, случайно указали в тексте сообщения

2021-11-20 08:11 UTC, h31 commented on lab1/client.py
> +sock.connect(('localhost', 12345))
Можно ли сделать так, чтобы адрес мог задавать пользователь, не меняя при этом программу (не комментируя код и не добавляя новый вызов)?

2021-11-20 09:47 UTC, astudina commented on lab1/clientThread.py
> +            # except ConnectionResetError:
Исправили

2021-11-20 09:47 UTC, astudina commented on lab1/lab1.md
> +    - Изначально отправляются два сообщения: размер последующего сообщения и само сообщение, включающее флаг о наличии/
Добавили уточнение, что размер указывается в байтах

2021-11-20 09:49 UTC, astudina commented on lab1/client.py
> +        message_parts = message.split(' & ')
Если & не сопровождается пробелами с обеих сторон, то проблем не возникнет, и он будет воспринят как часть сообщения. В противном случае часть после & будет проверена на то, является ли это путём к файлу на компьютере клиента. Если нет, то будет выведено сообщение о некорректном формате ввода

2021-11-20 09:50 UTC, astudina commented on lab1/client.py
> +sock.connect(('localhost', 12345))
Добавили возможность ввода адреса пользователем (по умолчанию будет использоваться localhost)

2021-11-23 22:16 UTC, h31 requested changes

2021-11-23 22:16 UTC, h31 commented on lab1/client.py
> +        message_parts = message.split(' & ')
```
раз & два & три
```
Как в таком случае будет обработана часть `три`?

2021-11-23 22:16 UTC, h31 commented on lab1/client.py
> +if address == '':
Можно просто `if not address`. Можно не исправлять.

2021-11-25 12:40 UTC, astudina commented on lab1/client.py
> +        message_parts = message.split(' & ')
Исправили этот момент. Теперь путём к файлу считается часть введённого текста после последнего &. Остальное отправляется как сообщение.

2021-11-27 11:39 UTC, h31 approved these changes

2021-12-02 16:27 UTC, closed without merging