Leonid Khvatskin, 3530901/80203] Lab 3
h31/NetworksLab2021 pull request #29
Opened 2021-11-22 16:25 UTC by TheGreenBeaver

2021-11-22 16:30 UTC, TheGreenBeaver commented
Комментарий к [этому](https://github.com/h31/NetworksLab2021/pull/29/commits/fee7aa46a9618810654a2b4bdafd8f4a0b219d5a) и [этому](https://github.com/h31/NetworksLab2021/pull/29/commits/868ea159c28d2134fa1d5d3926e0144839a9736e) коммитам:
Для сервера внутренние методы SlipHandler (find_border, escape_characters и т.д.) ещё не тестировались, так что я оставил их публичными, чтобы можно было тестировать их отдельно. Для клиента же они уже прошли испытание первой лабой, так что я оставил публичным только свежесозданный makeHeader (по той же причине - чтобы протестить отдельно), feed и makeMessage (потому что именно ими пользуемся процессе работы приложения)

2021-12-08 11:45 UTC, h31 requested changes

2021-12-08 11:45 UTC, h31 commented on server/pillow/index.py
> +SUCCESS_THRESHOLD = 200
Скорее `range`, кмк

2021-12-08 11:45 UTC, h31 commented on server/pillow/index.py
> +request_shape = {
Обычно это называют schema. Не смотрели [готовые библиотеки](https://stackoverflow.com/questions/45812387/how-to-validate-structure-or-schema-of-dictionary-in-python) для проверки схемы?

2021-12-08 11:45 UTC, h31 commented on server/util/misc.py
> +        item = arr[i]
`enumerate`

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +import util.misc as _
Идею, видимо, взяли из lodash? Может, просто импортировать из файла все функции (`*`)?

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +            cb: Callable = lambda: None
Не очень понятное имя аргумента. Понятно, что callback, но для чего - непонятно. Может, `on_done` или `on_sent`?

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +            chunk = await self.reader.read(2 ** 30)
Почему такой большой буфер?

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +                payload = pillow.validate_request(deserialized_body)
Если вы возвращаете тот же объект, то можно не создавать новую переменную (`payload`). Иначе можно подумать, что `validate_request` как-то меняет объект, что не согласуется с названием функции.

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +                await self.__getattribute__(f'handle_{_.snake_case(action)}')(action=action, data=data)
Насколько такая схема надёжна? Не может ли она вызвать проблемы с безопасностью (а-ля `eval`)? Не будет ли вызывать непонятных исключений, если такого метода нет?

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +        duplicate_username = _.find(self.server_ref.clients, lambda client, *_: client.username == username)
Может, просто сделать словарь с именами? С учетом того, что `find` нигде больше не используется, это может и повысить эффективность поиска, и сократить код.

2021-12-08 11:45 UTC, h31 commented on server/toss_client_holder.py
> +        if duplicate_username or no_username:
Есть ощущение, что если разделить этот `if` на две ветки, код будет немного понятнее

2021-12-08 11:45 UTC, h31 commented on server/toss_server.py
> +            filter_clients: Callable[[List[TossClientHolder]], List[TossClientHolder]] = lambda lst: lst,
Кажется, схема с несколькими коллбеками несколько переусложняет код. Например, я не нашёл, где явно задается аргумент `filter_clients`.

2021-12-08 11:45 UTC, h31 commented on server/toss_server.py
> +        # SOCK_STREAM means this is a TCP socket - set by default internally
К чему относится этот комментарий?

2021-12-08 23:46 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +            chunk = await self.reader.read(2 ** 30)
Возможно, я не до конца разобрался, как вообще работает этот аргумент... Насколько я понял, это по сути максимальное количество данных, которое разрешено считывать за один раз; в документации пишут, что можно вовсе не указывать его, и тогда чтение будет происходить "до упора", но на практике такой способ у меня не сработал. Так что я указал нарочно заоблачное число (1гб), чтобы на минимизировать вероятность ситуации, когда приходящие данные дополнительно дробятся из-за того, что мы усановили слишком низкий потолок

2021-12-08 23:47 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +                await self.__getattribute__(f'handle_{_.snake_case(action)}')(action=action, data=data)
Если action не из списка разрешённых, данные просто не пройдут валидацию, и до этого момента программа вообще не дойдёт

2021-12-08 23:53 UTC, TheGreenBeaver commented on server/toss_server.py
> +        # SOCK_STREAM means this is a TCP socket - set by default internally
Изначально (пока не нашёл `asincio`-обёртку) создавал сервер с помощью `sock.socket`, подписал для себя, чтобы не дёргаться каждый раз, как только глаз цепляется за константы. Для `asyncio.start_server` `type` уже под капотом выставлен в `SOCK_STREAM`, о чём я тоже постоянно забывал и каждый полчаса лез в доки проверить, почему `type` не выставлен
Короче говоря, - комменты для борьбы с собственной паранойей

2021-12-09 00:01 UTC, TheGreenBeaver commented on server/pillow/index.py
> +SUCCESS_THRESHOLD = 200
Почему же? Это ведь не промежуток "с такого-то статуса по такой-то", а граница: меньше - ОК, больше или равно - ошибка

2021-12-09 00:08 UTC, TheGreenBeaver commented on server/util/misc.py
> +        item = arr[i]
Исправил, не знал, что такая функция есть

2021-12-09 00:14 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +import util.misc as _
Да, lodash, разумеется, - даже нейминг не менял. Импорты поправил

2021-12-09 00:30 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +            cb: Callable = lambda: None
Повторял node.js-овский нейминг; возможно, он действительно не слишком понимабельный, если читать без контекста. Поменял на `on_success`

2021-12-09 00:38 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +                payload = pillow.validate_request(deserialized_body)
Действовал по аналогии с джангой: там сериалайзер возвращает новый объект. Здесь, конечно, в этом смысла никакого нет - убрал лишнюю переменную

2021-12-09 00:53 UTC, TheGreenBeaver commented on server/toss_server.py
> +            filter_clients: Callable[[List[TossClientHolder]], List[TossClientHolder]] = lambda lst: lst,
Именно **коллбек** тут всего один - `cb`; впрочем, он нигде не используется (остался как рудимент от соответствующего кода на node.js из первой лабы), так что я убрал его, так же как и `filter_clients` (изначально предполагал, что для каких-то actions придётся бродкастить выборочно, а не всем доступным клиентам)

2021-12-09 00:54 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +        if duplicate_username or no_username:
Попробовал разбить на две ветки - имхо, понятнее не стало) Может, как-то неправильно разбиваю...

2021-12-09 00:57 UTC, TheGreenBeaver commented on server/toss_client_holder.py
> +        duplicate_username = _.find(self.server_ref.clients, lambda client, *_: client.username == username)
В рамках конкретно данной работы, наверное, действительно можно. Но мне такой подход не очень нравится, как бы это сказать... *Архитектурно*. Это как иметь в базе данных таблицу app_user и отдельно app_user_name - получается неоднозначность, дублирование данных, да и вообще всю инфу о клиенте хочется иметь внутри объекта этого самого клиента

2021-12-11 09:50 UTC, h31 approved these changes

2021-12-17 01:43 UTC, closed without merging