Цаплин Илья. Лабораторная работа№2
h31/NetworksLab2021 pull request #33
Opened 2021-11-26 18:47 UTC by TsaplinIA

2021-12-17 22:55 UTC, h31 requested changes

2021-12-17 22:55 UTC, h31 commented on PackageHandler.py
> +		parts = self.file_name.split(".")
`partition`?

2021-12-17 22:55 UTC, h31 commented on PackageHandler.py
> +			if self.address != addr: # �� ������, ���� ������ ������� ����� �����, � ����� ��������
Съехала кодировка. Используйте UTF-8

2021-12-18 08:23 UTC, TsaplinIA commented on PackageHandler.py
> +			if self.address != addr: # �� ������, ���� ������ ������� ����� �����, � ����� ��������
Исправил

2021-12-18 08:25 UTC, TsaplinIA commented on PackageHandler.py
> +		parts = self.file_name.split(".")
Такой формат предлагает PyCharm.(Если я правильно понял, и комментарий относится к разделению функций всего одной строкой)

2021-12-19 19:07 UTC, h31 approved these changes

2021-12-20 18:56 UTC, closed without merging