Tarasenko Tanashkin 3530901/80203 - Lab2
h31/NetworksLab2021 pull request #34
Opened 2021-11-27 10:39 UTC by GetRhymes

DNSProtocol (server + client)

2021-12-03 18:05 UTC, h31 requested changes

2021-12-03 18:05 UTC, h31 commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +        transactionId = getShortFromTwoBytes(byteArray[0] to byteArray[1])
[slice?](https://kotlinlang.org/docs/collection-parts.html#slice)

2021-12-03 18:05 UTC, h31 commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +    fun mapperMessage(byteArray: ByteArray, prevMessage: DNSMessage? = null) {
factory method?

2021-12-03 18:05 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +    public CommunicatorService() throws SocketException, UnknownHostException {
Пройдитесь по коду инспекциями

2021-12-03 18:05 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                e.printStackTrace();
Не очень понимаю логику. У нас ошибка передачи, непонятно, было ли что-либо принято в `buf`, почему мы продолжаем обработку?

2021-12-03 18:05 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                System.out.print(b + " ");
Если это отладочный лог, то используйте функции для логирования

2021-12-03 18:05 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                buf = new byte[2048];
Почему бы `buf` не сделать просто локальной переменной, чтобы не очищать каждый раз?

2021-12-03 18:05 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +    private static byte[] hexStringToByteArray(String s) {
Поставьте ссылку на [источник](https://stackoverflow.com/a/140861), как мы договаривались

2021-12-03 18:05 UTC, h31 commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSFlags.kt
> +    private fun bitOperation(value: Boolean, shift: Int) {
Из имени метода сложно понять, что он делает

2021-12-03 18:05 UTC, h31 commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +//        for (ans in answers) {
Почистите код от закомментированных строк

2021-12-03 18:05 UTC, h31 commented on dnsClient/src/main/java/com/dns/client/console/ConsoleListener.java
> +    private String getA(byte[] bytesIp) {
Если у вас есть классы для разных типов ответов (`DNSAnswer`), почему бы не переместить этот код туда?

2021-12-04 08:47 UTC, NastyPill commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +        transactionId = getShortFromTwoBytes(byteArray[0] to byteArray[1])
в других случаях заменили, здесь, кажется, нужна именно пара, т.к. целевое кол-во параметров этого метогда всегда два, и, мне кажется, странно было бы передавать не пару, а list

2021-12-04 08:48 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +    private static byte[] hexStringToByteArray(String s) {
поставили

2021-12-04 08:50 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                e.printStackTrace();
исправил логику на:
```
            try {
                socket.send(packet);
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                buf = new byte[2048];
            }
```

2021-12-04 08:50 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                System.out.print(b + " ");
убрали лог

2021-12-04 08:52 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                buf = new byte[2048];
вынесли в локальную переменную

2021-12-04 08:54 UTC, NastyPill commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +//        for (ans in answers) {
почистили

2021-12-04 09:01 UTC, NastyPill commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSFlags.kt
> +    private fun bitOperation(value: Boolean, shift: Int) {
поправили имена

2021-12-04 09:04 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                e.printStackTrace();
Насчет `buf` не особо понял, что вы имеете ввиду.
А здесь, если мы не можем по каким-то причинам отправить, мы просто продолжаем работу.

2021-12-04 09:06 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +    public CommunicatorService() throws SocketException, UnknownHostException {
Удалили все ненужное

2021-12-04 09:20 UTC, NastyPill commented on dnsClient/src/main/java/com/dns/client/console/ConsoleListener.java
> +    private String getA(byte[] bytesIp) {
Проговорили, решили не менять

2021-12-08 15:24 UTC, NastyPill commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +        transactionId = getShortFromTwoBytes(byteArray[0] to byteArray[1])
- [ ] все методы подобные этому на list

2021-12-08 15:24 UTC, NastyPill commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +    fun mapperMessage(byteArray: ByteArray, prevMessage: DNSMessage? = null) {
- [ ] factory method

2021-12-08 15:24 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                e.printStackTrace();
- [ ] изменить логику

2021-12-08 16:36 UTC, NastyPill commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +    fun mapperMessage(byteArray: ByteArray, prevMessage: DNSMessage? = null) {
подумали с Никитой о factory методе, на самом деле, не очень поняли, зачем он нам здесь нужен. 
А вот, по поводу того, что тут наполняем созданный объект, решили создать конструктор, который бы выполнял эту логику. Т.е. сейчас, по сути, можем создать этот объект из ByteArray и prevMessage

2021-12-08 16:37 UTC, NastyPill commented
@h31 поправили все замечания по данному ПР. Ждем апрува :)

2021-12-09 13:20 UTC, h31 approved these changes
Принимаю работу

2021-12-09 13:20 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                buf = new byte[2048];
Зачем?

2021-12-09 13:20 UTC, h31 commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                continue;
Насколько есть смысл оставаться в цикле, если у возникла ошибка?

2021-12-09 13:21 UTC, h31 commented on DNSHelper/src/main/java/com/poly/dnshelper/model/DNSMessage.kt
> +    fun mapperMessage(byteArray: ByteArray, prevMessage: DNSMessage? = null) {
Да, тоже вариант

2021-12-10 23:41 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                buf = new byte[2048];
Считаем, что в буфер что-то попало, но т.к. словили ошибку, то продолжаем работу с пустым буфером, чтоб он ни на что не аффектил

2021-12-10 23:45 UTC, NastyPill commented on dnsServer/src/main/java/com/dns/server/service/CommunicatorService.java
> +                continue;
Т.к. используем UDP, который не гарантирует ничего, могут быть разные приколы при пересылке по сети, которые протокол не разрулит. Т.О. кажется, при "могрании" сети не стоит завершать работу, а продолжить принимать поступающие сообщения "с чистого листа"

2021-12-17 00:37 UTC, closed without merging