Lab3[Курняков Пётр, Невоструева Яна]
h31/NetworksLab2021 pull request #35
Opened 2021-12-01 16:49 UTC by pupptmstr

2021-12-03 19:12 UTC, h31 requested changes

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +    private val host = host_
Зачем нужна отдельная переменная?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +                    if (receiver.availableForRead > 0) {
В проекте похожая строчка повторяется несколько раз. Есть подозрение, что подобная реализация будет вызывать высокую нагрузку CPU. Можете проверить?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +                when (val userMessage = readLine()) {
`readLine()` блокирующий. Не будет ли это вызывать проблем?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +            //receiver.close()
Почистите исходники от закомментированного кода

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +            while (stillWorking) {
Почему цикл?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/ClientList.kt
> +            writeChannel.writeFully(message)
Эти же строчки повторяются чуть выше в файле

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/ClientList.kt
> +        socketList[id]!!.close()
IDEA ругается на `close()`. Насколько обоснованно?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/ClientList.kt
> +                    val messageBuffer = message.getMessage().plus(fileByteArray)
Как в Kotlin можно написать это же чуть проще?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/Main.kt
> +            val arg = parseHostAndPort(args[serverArgumentIndex])
Как программа будет работать с такими аргументами: `server:port -s`?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/MessageState.kt
> +enum class MessageState {
Лишний файл?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/Main.kt
> +            } catch (e: Exception) {
Немного напрягает, что в нескольких местах программы мы ловим любой `Exception`, но при этом считаем, что источником ошибок могут быть только проблемы с подключением

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +    val timeRegex =
Давайте обсудим на занятии, что можно сделать с таким кодом

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +        Pair("127.0.0.1", 8081)
Насколько ОК молча подставлять другие параметры, если произошла какая-то ошибка? К чему это может привести?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/server/Server.kt
> +            var isWorking = true
Нужен ли этот флаг?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/server/Server.kt
> +            val receiver = clientList.getReadChannel(clientId) ?: throw NullPointerException()
Насколько `NullPointerException` подходящий тип исключения?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/server/Server.kt
> +                        println(
Если это отладочный вывод, можем ли мы использовать библиотеку логирования для этого?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/server/Server.kt
> +        } catch (e: Exception) {
См. комментарий выше про обработку исключений

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +                "-s host:port - запуск клиента с кастомными хостом и портом\n" +
Точно клиента?

2021-12-03 19:12 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +    val split = fileName.split(".")
Как этот код будет работать, если имя файла - `archive.tar.gz`?

2021-12-03 19:39 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +        Pair(arg.split(":")[0], arg.split(":")[1].toInt())
Как такой код будет работать с IPv6?

2021-12-04 08:27 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +        Pair(arg.split(":")[0], arg.split(":")[1].toInt())
Когда мы пытаемся программными средствами посмотреть на каком адресе запущен, например, Сервер (именно IPv6), то получаем [0:0:0:0:0:0:0:0]:8081. Переделали запись аргументов пользователя именно под такой формат записи

2021-12-04 08:27 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +    val split = fileName.split(".")
исправлено

2021-12-04 08:27 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +                "-s host:port - запуск клиента с кастомными хостом и портом\n" +
исправлено

2021-12-04 08:28 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/Main.kt
> +            val arg = parseHostAndPort(args[serverArgumentIndex])
аргументы должны идти в "верном" порядке, как указано в HELP
добавлена проверка, про таких аргументах клиент увидит сообщение Incorrect arguments и получит в подсказку HELP

2021-12-04 08:42 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +        Pair("127.0.0.1", 8081)
Не ОК
Клиент может подключиться совсем не туда куда он хотел и получить неожиданную для себя функциональность
Следует сообщать об этом клиенту о неверно введенных аргументах
исправлено

2021-12-04 08:47 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +    private val host = host_
Исправлено
Теперь клиент создается без аргументов, а вот стартует уже на определенном хосте и порте

2021-12-04 08:48 UTC, pupptmstr commented on lab3/src/main/kotlin/com/monkeys/pcss/models/ClientList.kt
> +        socketList[id]!!.close()
Не очень обосновано
Объясним на паре

2021-12-04 08:51 UTC, pupptmstr commented on lab3/src/main/kotlin/com/monkeys/pcss/models/MessageState.kt
> +enum class MessageState {
???

2021-12-04 08:53 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +            //receiver.close()
исправлено

2021-12-04 08:55 UTC, pupptmstr commented on lab3/src/main/kotlin/com/monkeys/pcss/models/MessageState.kt
> +enum class MessageState {
Да, остатки предыдущих решений

2021-12-04 09:27 UTC, NevostruevaYana commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +                when (val userMessage = readLine()) {
исправлено

2021-12-11 08:21 UTC, h31 approved these changes

2021-12-11 08:27 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +            logger.error(e.stackTraceToString())
Зачем `stackTraceToString()`?

2021-12-11 08:40 UTC, pupptmstr commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +            logger.error(e.stackTraceToString())
А как в логгер это передавать? localizedMessage? Он вроде не выводит полный стектрейс

2021-12-14 15:59 UTC, closed without merging

2021-12-17 01:43 UTC, h31 commented on lab3/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +            logger.error(e.stackTraceToString())
https://www.baeldung.com/slf4j-log-exceptions