Lab3 [Бедрин Алексей, Медведев Данил]
h31/NetworksLab2021 pull request #38
Opened 2021-12-03 11:51 UTC by HaveAHeart

2021-12-17 01:21 UTC, h31 requested changes

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Server.kt
> +                    is SocketException, is NullPointerException -> {
Во-первых, зачем `when`, если можно сделать две ветки `catch`?

Во-вторых, обрабатывать NPE - [плохая идея](https://wiki.sei.cmu.edu/confluence/display/java/ERR08-J.+Do+not+catch+NullPointerException+or+any+of+its+ancestors). Лучше сделать так, чтобы такое исключение не возникало.

2021-12-17 01:21 UTC, h31 commented on README.md
> +-- Время заполняется сервером автоматически, при получении сообщения от клиента. Время задаётся в формате: YYYY-MM-SSTHH:mm:ssZ
У этого формата есть название

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Server.kt
> +            writer.writeFully(ByteBuffer.wrap(customMessage.toString().toByteArray()))
Dup

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Server.kt
> +                        println("$nickname disconnected; ${clientSockets.keys.size} remains connected.")
Сообщение явно из разряда логирования, используйте для этого соответствующие инструменты вместо `println`

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Client.kt
> +            pathStr = pathStr.substring(4, pathStr.length - 1) //try to get the insides...
Если используете группы, то почему бы не использовать их для получения _the insides_ вместо того, чтобы использовать `substring`?

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Server.kt
> +                writer.writeFully(ByteBuffer.wrap(customMessage.toString().toByteArray()))
Устраните, пожалуйста, дублирование кода. 4 раза повторяется `writeFully`, 3 раза повторяется `closeAll`

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Utils.kt
> +        emit(Pair(type, value))
А если в сообщении есть `: `? Как будет работать такой код?

2021-12-17 01:21 UTC, h31 commented on src/main/kotlin/Models/CustomSocket.kt
> +    var reader = aSocket.openReadChannel()
`val`?

2021-12-17 11:23 UTC, HaveAHeart commented on README.md
> +-- Время заполняется сервером автоматически, при получении сообщения от клиента. Время задаётся в формате: YYYY-MM-SSTHH:mm:ssZ
fixed, написал про ISO 8601

2021-12-17 11:24 UTC, HaveAHeart commented on src/main/kotlin/Server.kt
> +            writer.writeFully(ByteBuffer.wrap(customMessage.toString().toByteArray()))
fixed

2021-12-17 11:25 UTC, HaveAHeart commented on src/main/kotlin/Server.kt
> +                        println("$nickname disconnected; ${clientSockets.keys.size} remains connected.")
fixed, используем Logger

2021-12-17 11:25 UTC, HaveAHeart commented on src/main/kotlin/Server.kt
> +                writer.writeFully(ByteBuffer.wrap(customMessage.toString().toByteArray()))
fixed

2021-12-17 11:26 UTC, HaveAHeart commented on src/main/kotlin/Utils.kt
> +        emit(Pair(type, value))
Засплитит сообщение на 2 части по первому найденному двоеточию, а так как первое двоеточие всегда наше (между префиксом и самим сообщением), то всё сплитится корректно

2021-12-17 11:26 UTC, HaveAHeart commented on src/main/kotlin/Models/CustomSocket.kt
> +    var reader = aSocket.openReadChannel()
fixed

2021-12-17 13:08 UTC, HaveAHeart commented on src/main/kotlin/Server.kt
> +                    is SocketException, is NullPointerException -> {
fixed, NPE не болжен вылетать в этом месте вообще -> один блок catch только для SocketException

2021-12-17 13:10 UTC, HaveAHeart commented on src/main/kotlin/Client.kt
> +            pathStr = pathStr.substring(4, pathStr.length - 1) //try to get the insides...
fixed, используем matcher.group(1)

2021-12-17 21:54 UTC, h31 approved these changes
Принято

2021-12-17 21:54 UTC, h31 commented on src/main/kotlin/Utils.kt
> +        val msg = reader.readUTF8Line() ?: ""
Сильно не уверен, что это правильное исправление. Если возникла проблема, на неё нужно отреагировать (выбросить исключение, отключить клиента), а не просто игнорировать. К сожалению, документация Ktor не очень много говорит про то, когда конкретно у нас возникает `null`

2021-12-17 23:59 UTC, dVede commented on src/main/kotlin/Utils.kt
> +        val msg = reader.readUTF8Line() ?: ""
Алексей просто не совсем корректно написал. Я посмотрел сурсы ktor и увидел, что null он возвращает только в случае, когда "строка без символа конца строки или канал был закрыт, и никакие символы не были прочитаны".

![image](https://user-images.githubusercontent.com/43070399/146618510-df480a8d-04fa-43da-97f1-b5d1733507a8.png)

Теперь перейдем к самому интересному.
Если посмотреть на имеющийся код, то сейчас мы ловим только SocketException. Единственный метод, который может его вызвать в блоке try/catch это именно метод "readUTF8line()". Немного пошерстив код удалось найти, где это происходит.
 
![image](https://user-images.githubusercontent.com/43070399/146619419-e1e9ea2b-4517-4ae0-a741-f2242beef3b4.png)

Из двух случаев, второй у нас обрабатывается успешно, а вот первый (может произойти при неверной реализации клиента, когда нет символа конца строки) в теории реален. Поэтому теперь вместо пустой строки просто выкидываем SocketException(), обработка которого у нас уже реализована.

2021-12-18 02:56 UTC, dVede commented on src/main/kotlin/Utils.kt
> +        val msg = reader.readUTF8Line() ?: ""
После нормального закрытия сокета удалось получить null. Теперь сокеты закрываются нормально, exitProcess(0) вызывается только в случае закрытия севера. Также теперь в catch не SocketException(), а Throwable(), так как существуют разные причины закрытия сокета (блоке try/catch есть только один метод, который может выкинуть Throwable(), он будет срабатывать только в случаях ошибок связанных с сокетом).

2021-12-20 18:58 UTC, closed without merging