Lab 1. [Трачук Илья, Филимонов Артем]
h31/NetworksLab2021 pull request #40
Opened 2021-12-03 22:04 UTC by BigArtemka

2021-12-17 01:58 UTC, h31 requested changes
Не хватает описания протокола

2021-12-17 01:58 UTC, h31 commented on attachment/test.txt
> +gavno zalupa penis her
Вас ничего не смущает?

2021-12-17 01:58 UTC, h31 commented on src/main/java/org/example/server/Server.java
> +            out.write(Arrays.copyOf(content, content.length));
Зачем `Arrays.copyOf`?

2021-12-17 01:58 UTC, h31 commented on src/main/java/org/example/client/Client.java
> +            in = new BufferedInputStream(socket.getInputStream());
Можем получить NPE, если до этого возникло исключение

2021-12-17 01:58 UTC, h31 commented on src/main/java/org/example/client/Client.java
> +            Client.this.downService();
Зачем `Client.this`?

2021-12-17 01:58 UTC, h31 commented on src/main/java/org/example/client/Client.java
> +                        String[] f = attName.split("\\.");
Как такой код будет работать с файлов `archive.tar.gz`?

2022-02-06 16:17 UTC, BigArtemka commented on src/main/java/org/example/server/Server.java
> +            out.write(Arrays.copyOf(content, content.length));
Исправлено

2022-02-06 16:17 UTC, BigArtemka commented on src/main/java/org/example/client/Client.java
> +            in = new BufferedInputStream(socket.getInputStream());
Исправлено

2022-02-06 16:17 UTC, BigArtemka commented on src/main/java/org/example/client/Client.java
> +            Client.this.downService();
Исправлено

2022-02-06 16:20 UTC, BigArtemka commented on src/main/java/org/example/client/Client.java
> +                        String[] f = attName.split("\\.");
Проверили с архивами,  работает корректно.

2022-02-10 16:08 UTC, h31 commented on src/main/java/org/example/client/Client.java
> +            in = new BufferedInputStream(socket.getInputStream());
Всё ещё можете получить NPE в `downService`

2022-02-10 16:15 UTC, h31 commented on src/main/java/org/example/client/Client.java
> +                        String[] f = attName.split("\\.");
Не очень понимаю, как вы проверили. Если у нас `split` выдает массив из трех элементов, куда попадает третий?

2022-02-10 16:17 UTC, h31 commented on src/main/java/org/example/client/Client.java
> +            in = new BufferedInputStream(socket.getInputStream());
Почему-то мой [комментарий](https://github.com/h31/NetworksLab2021/pull/40/files#r803840755) не отображается здесь, продублирую

2022-02-10 16:17 UTC, h31 commented
Всё ещё нет описания протокола

2022-02-12 12:16 UTC, kuchartI commented on src/main/java/org/example/client/Client.java
> +            in = new BufferedInputStream(socket.getInputStream());
Исправлено

2022-02-12 12:16 UTC, kuchartI commented on src/main/java/org/example/client/Client.java
> +                        String[] f = attName.split("\\.");
Исправлено

2022-03-22 09:50 UTC, h31 approved these changes

2022-03-22 09:50 UTC, closed without merging