Lab3 [Никифоров Тимофей, Васильев Роман][3530901/80203]
h31/NetworksLab2021 pull request #43
Opened 2021-12-04 07:51 UTC by nikiforovta

2021-12-10 12:23 UTC, nikiforovta commented
@h31 Добрый день! Проверьте, пожалуйста, исправления

2021-12-15 11:34 UTC, h31 requested changes
1) Рефакторинг клиента, убрать sleep
2) Убрать dead code в сервере, исправить проблему с русским текстом

2021-12-15 15:17 UTC, killawetz commented
@h31 Замечания исправлены.

2021-12-17 01:37 UTC, h31 approved these changes
Принято

2021-12-17 01:37 UTC, h31 commented on lab3/server/src/main/java/Tool.java
> +        } catch (IndexOutOfBoundsException e) {
По возможности, [лучше](https://wiki.sei.cmu.edu/confluence/display/java/ERR08-J.+Do+not+catch+NullPointerException+or+any+of+its+ancestors) не перехватывать unchecked exception, а писать код, который бы не создавал подобные исключения. В данном случае можно просто заранее проверить длину массива.

2021-12-17 01:37 UTC, h31 commented on lab3/server/src/main/java/Tool.java
> +            e.printStackTrace();
Сообщение - явно из разряда логирования, используйте для этого соответствующие инструменты

2021-12-20 18:58 UTC, closed without merging