Lab4.1 Tarasenko - Tanashkin
h31/NetworksLab2021 pull request #47
Opened 2021-12-11 09:12 UTC by GetRhymes

Tarasenko - server 
Tanaskin - client

2021-12-15 12:49 UTC, GetRhymes commented
https://github.com/GetRhymes/WebShop

2021-12-16 10:45 UTC, GetRhymes commented
Починил pr, теперь здесь есть все и сервер и клиент

2021-12-17 22:27 UTC, h31 requested changes

2021-12-17 22:27 UTC, h31 commented on ShopClient/src/main/java/com/shop/cli/ConsoleInterface.java
> +                    Integer id = Integer.parseInt(commandParts[1]);
Пройдитесь по коду инспекциями. И в клиенте, и в сервере

2021-12-17 22:27 UTC, h31 commented on ShopClient/src/main/java/com/shop/rest/RestService.java
> +                .url(new URL(HOST + BASE_URL + "/all"))
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/

2021-12-17 22:27 UTC, h31 commented on WebShop/src/main/kotlin/com/webshop/server/controller/ShopController.kt
> +        if (shopService == null) throw ClassNotFoundException("ShopService was not found")
`requireNotNull`?

2021-12-17 22:27 UTC, h31 commented on WebShop/src/main/kotlin/com/webshop/server/controller/ShopController.kt
> +        else {
Нужно ли здесь писать `else`?

2021-12-17 22:37 UTC, GetRhymes commented on WebShop/src/main/kotlin/com/webshop/server/controller/ShopController.kt
> +        if (shopService == null) throw ClassNotFoundException("ShopService was not found")
не знал о такой функции, исправил

2021-12-17 22:37 UTC, GetRhymes commented on WebShop/src/main/kotlin/com/webshop/server/controller/ShopController.kt
> +        else {
не нужно :) исправил на requireNotNull

2021-12-18 09:16 UTC, NastyPill commented on ShopClient/src/main/java/com/shop/rest/RestService.java
> +                .url(new URL(HOST + BASE_URL + "/all"))
Поправил

2021-12-18 14:25 UTC, h31 approved these changes

2021-12-22 21:25 UTC, closed without merging