Lab4.2 Tanashkin Tarasenko WEB_FORUM
h31/NetworksLab2021 pull request #48
Opened 2021-12-11 10:59 UTC by GetRhymes

Tanaskin - server
Tarasenko -client

2021-12-15 12:48 UTC, h31 requested changes
1) Url class
2) Thread-safety in server

2021-12-17 22:38 UTC, h31 requested changes

2021-12-17 22:38 UTC, h31 commented on WebForum/Forum/src/main/java/com/forum/repo/UserRepository.java
> +    private boolean isUserExists(String username) {
Лишняя функция?

2021-12-17 22:38 UTC, h31 commented on WebForum/Forum/src/main/java/com/forum/security/CustomWebSecurityConfigurerAdapter.java
> +import org.springframework.security.provisioning.InMemoryUserDetailsManager;
Лишние импорты

2021-12-17 22:38 UTC, h31 commented on ForumClient/src/main/kotlin/com/forum/client/service/ForumService.kt
> +            "$domainName$BASE_URL_FORUM$ALL_MESSAGES" + "$PATH_SEP${packetMessageDTO.mainTheme}" +
Не вижу смысла в `$PATH_SEP`. Это же не путь в ФС, тут он всегда `/`

2021-12-17 22:38 UTC, h31 commented on ForumClient/src/main/kotlin/com/forum/client/service/ForumService.kt
> +            "$domainName$BASE_URL_FORUM$ALL_MESSAGES" + "$PATH_SEP${packetMessageDTO.mainTheme}" +
Посмотрите в соседний PR, я там добавил ссылку на класс с билдером URL

2021-12-18 08:57 UTC, NastyPill commented on WebForum/Forum/src/main/java/com/forum/repo/UserRepository.java
> +    private boolean isUserExists(String username) {
удалена

2021-12-18 08:58 UTC, NastyPill commented on WebForum/Forum/src/main/java/com/forum/security/CustomWebSecurityConfigurerAdapter.java
> +import org.springframework.security.provisioning.InMemoryUserDetailsManager;
удалены

2021-12-18 08:59 UTC, GetRhymes commented on ForumClient/src/main/kotlin/com/forum/client/service/ForumService.kt
> +            "$domainName$BASE_URL_FORUM$ALL_MESSAGES" + "$PATH_SEP${packetMessageDTO.mainTheme}" +
сделано

2021-12-18 14:25 UTC, h31 approved these changes

2021-12-22 21:25 UTC, closed without merging