Lab4.1 Терминал Клиент + Сервер[Курняков Пётр, Невоструева Яна]
h31/NetworksLab2021 pull request #51
Opened 2021-12-15 12:07 UTC by pupptmstr

2021-12-25 18:13 UTC, pupptmstr commented
@h31

2021-12-28 17:23 UTC, h31 requested changes

2021-12-28 17:23 UTC, h31 commented on lab4/forum/client/src/main/kotlin/com/monkeys/Application.kt
> +    private fun printThemesBeauty(themes: Map<String, List<String>>) {
Это обычно называется pretty print
https://en.wikipedia.org/wiki/Prettyprint

2021-12-28 17:23 UTC, h31 commented on lab4/forum/client/src/main/kotlin/com/monkeys/ForumService.kt
> +                append(HttpHeaders.Authorization, TOKEN_PREF + token)
Этот код повторяется несколько раз. Можем ли мы убрать дублирование?

2021-12-28 17:23 UTC, h31 commented on lab4/forum/client/src/main/kotlin/com/monkeys/ForumService.kt
> +        return response.status == HttpStatusCode.OK
А если ошибка?

2021-12-28 17:23 UTC, h31 commented on lab4/forum/client/src/main/kotlin/com/monkeys/Utils.kt
> +fun getURL(request: String) = "$HTTP_PREF$HOST:$PORT$request"
URL Builder?
https://stackoverflow.com/a/64432035

2021-12-28 17:23 UTC, h31 commented on lab4/forum/client/src/test/kotlin/com/monkeys/ApplicationTest.kt
> +class ApplicationTest {
Насколько нужен этот код?

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/api/ApiRoutes.kt
> +                get("/message-list/{sub-theme}") {
FYI: обычно это переводится как topic

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/controller/UserController.kt
> +            val connection = getConnection()!!
`use`?

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/Utils.kt
> +    val psw = varchar("psw")
FYI: обычно так password [не сокращают](https://en.wiktionary.org/wiki/password#Synonyms). Да и в целом не вижу смысла использовать сокращения, если слова не очень длинные

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/client/src/main/kotlin/com/monkeys/models/response/ResponseAuthModel.kt
> +data class ResponseAuthModel (
Такие объекты обычно называют [DTO](https://ru.wikipedia.org/wiki/DTO), а не моделями

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/models/Roles.kt
> +enum class Roles {
Лишний код?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/client/src/main/kotlin/com/monkeys/plugins/HTTP.kt
> +fun Application.configureHTTP() {
Где-нибудь используется?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/api/UserController.kt
> +                    "[F]" + it.name
А если на стороне клиента у нас для файлов и директорий будут разные иконки, как мы сможем их различать? Можем, конечно, смотреть первые символы в имени, но есть ли более надёжные и аккуратные способы?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/api/UserController.kt
> +        val res = mutableListOf<String>()
Можно ли сделать это на обычном списке, не мутабельном?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/models/response/ResponseModel.kt
> +interface ResponseModel<T> {
См. комментарий про DTO

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/Utils.kt
> +        //return resSet.next()
Почему закомментировано?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/Utils.kt
> +        val timestampMinusHour = if (instantMinusHour != null) Timestamp.from(instantMinusHour) else null
1) Может ли эта переменная быть null?
2) Если она null, то как это будет работать в SQL-запросе?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/Utils.kt
> +                "SELECT * FROM users WHERE (LOGIN='$login' AND is_active=true AND (active_last, active_last) OVERLAPS ('$timestampMinusHour', INTERVAL '1 hour'));"
Что будет, если я как пользователь укажу логин `'; DROP TABLE users;`? Как от этого можно защититься?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/server/src/main/kotlin/com/monkeys/terminal/api/UserController.kt
> +        return if (path.isDirectory) {
А если мы указали `locationToLs` равный `/someDir`, и такая директория есть внутри `baseLocation`? Обратите внимание на методы `isAbsolute()` и `resolve()`

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/controller/UserController.kt
> +                    connection.insert(MessageTable) {
FYI: Это правильное решение, но бороться с инъекциями можно и обычным `PreparedStatement`, не обязательно переписывать

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/controller/UserController.kt
> +            } else {
Этот код можно легко переписать так, чтобы основной сцерарий был вне `if`-а. ИМХО, так будет более читаемо

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/api/ApiRoutes.kt
> +    if (msg == "You have been inactive for 1 hour. Login again" ||
Мне не очень нравится решение, когда мы тип ошибки определяем по строке. Банально захотим перевести сообщение на другой язык и всё сломается. Можно ли определять тип ошибки по другим критериям? Например, если было исключение, то определять тип проблемы по классу исключения. Или (менее красивый вариант ИМХО) сделать enum для разных типов ошибок.

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/client/src/main/kotlin/com/monkeys/Utils.kt
> +fun getURL(request: String) = "$HTTP_PREF$HOST:$PORT$request"
См. комментарий к другому клиенту

2021-12-28 17:23 UTC, h31 commented on lab4/forum/client/src/main/kotlin/com/monkeys/Application.kt
> +                    "ls" -> {getMessageList(command.replace(commandSplit[0], "").trim())}
А если в имени директории будет `ls`?

2021-12-28 17:23 UTC, h31 commented on lab4/terminal/client/src/main/kotlin/com/monkeys/Application.kt
> +            print("Invalid input. Try to connect again")
Можно ли избавиться от `else` здесь?

2021-12-28 17:23 UTC, h31 commented on lab4/forum/server/src/main/kotlin/com/monkeys/controller/AuthController.kt
> +            "Error. Incorrect login or password"
При использовании функции мы всегда должны помнить, что вместо токена нам могут вернуть строку с кодом ошибки. Человек, который использует функцию, может об этом забыть, и тогда всё сломается. Как можно сделать, чтобы человек не забыл обработать этот случай?

2021-12-29 07:56 UTC, NevostruevaYana commented on lab4/forum/server/src/main/kotlin/com/monkeys/api/ApiRoutes.kt
> +                get("/message-list/{sub-theme}") {
ok

2022-01-20 18:27 UTC, h31 approved these changes

2022-01-20 18:28 UTC, closed without merging