Lab1 - 3530901/80203[Курняков Пётр, Невоструева Яна]
h31/NetworksLab2021 pull request #6
Opened 2021-09-26 21:31 UTC by pupptmstr

2021-09-26 21:32 UTC, pupptmstr commented
all commit history is here https://github.com/pupptmstr/pcss

2021-10-01 16:56 UTC, pupptmstr commented
Fixed:
1) Changes in time format(Теперь основную временную метку проставляет сервер, а смещениеобязан делать клиент)
2) Убраны лишние задержки и тп. Адекватно выглядит клиент

Additions:
1) Проверка на то, что файл - медиафайл

Troubles:
1) Хоть и переписано с base64 на обычный поток байт отправка файла, при использовании этого функционала почему-то выкидывает людей из чата. Ошибку найти пока не можем

2021-10-08 13:50 UTC, pupptmstr commented
Собственно наконец-то все баги исправлены, протокол доделан, мессенджер поверх него тоже.
Fixed:
1) Переписан и доделана отправка файлов потоком байт
2) Исправлен протокол, теперь есть поля размера файла и размера даты, а хэдэр фиксированного размера
3) Исправлены баги с вылетами участников и тд

Additions:
1) Аскии арты ко всем пресылаемым картинкам
2) Сообщения о присоеденении участников и их отключении
3) Сообщения о количестве участников при присоеденении к чату

2021-10-08 13:50 UTC, pupptmstr commented
@h31

2021-10-09 10:25 UTC, h31 requested changes

2021-10-09 10:25 UTC, h31 commented on lab1/README.md
> +   00000035
ASCII?

2021-10-09 10:25 UTC, h31 commented on lab1/README.md
> +   2021-10-01T15:28:16.976915+03:00{Europe/Moscow}. Клиент должен регулировать время на свое самостоятельно.
Зачем пояс?

2021-10-09 10:25 UTC, h31 commented on lab1/README.md
> +4) Поток байтов файла записать в конец мэссэджа, предварительно закодировав весь поток в Base64
???

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun restoreArguments(args: List<String>): WorkType = when {
?

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun kit(): String =
:)

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun getNewMessage(inputStream: BufferedInputStream): Pair<Message, ByteArray> {
Buffered?

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +    val sData = String(dataByteArray).replace("\u0000", "")
???

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun shapingFileName(fileName: String, senderName: String, time: String): String {
Имя

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun getFixedLengthString(dataSize: Int): String {
?

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/client/Client.kt
> +    private fun receivingMessages() {
Имя

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/models/AsciiArt.kt
> +                sb.append("${colorCodeIntoChar(colorCode)}")
?

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/models/message/Message.kt
> +    override fun equals(other: Any?): Boolean {
???

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +    val timeRegex =
Грамматики

2021-10-09 10:25 UTC, h31 commented on lab1/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +        """([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5]):((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|(
?

2021-10-09 10:27 UTC, pupptmstr commented on lab1/README.md
> +   00000035
Обсудили

2021-10-09 10:27 UTC, pupptmstr commented on lab1/README.md
> +   2021-10-01T15:28:16.976915+03:00{Europe/Moscow}. Клиент должен регулировать время на свое самостоятельно.
Обсудили

2021-10-09 10:29 UTC, pupptmstr commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun kit(): String =
Обсудили мем

2021-10-09 10:29 UTC, pupptmstr commented on lab1/src/main/kotlin/com/monkeys/pcss/Utils.kt
> +fun kit(): String =
это кот на украинском

2021-10-09 10:30 UTC, pupptmstr commented on lab1/src/main/kotlin/com/monkeys/pcss/models/message/Parser.kt
> +    val timeRegex =
Обсудили проблему, посмотрим

2021-10-09 11:01 UTC, pupptmstr commented
Fixes all discussions)

2021-10-09 11:52 UTC, h31 approved these changes

2021-10-22 18:46 UTC, closed without merging