Lab4_1 (сервер, калькулятор), Шрамков (Викторов)
h31/NetworksLab2021 pull request #61
Opened 2021-12-19 00:02 UTC by k1unk

2022-02-10 17:55 UTC, h31 requested changes

2022-02-10 17:55 UTC, h31 commented on calc.md
> +GET /plus?o1={Value}&o2={Value}&authorization={Value}
https://community.auth0.com/t/can-i-securely-pass-a-jwt-in-the-url-query-parameters-of-a-get-request/65678

2022-02-10 17:55 UTC, h31 commented on login.js
> +        let users = JSON.parse(JSON.stringify(exports.usersJSON))
Зачем преобразовывать в JSON, а затем делать обратную операцию?

2022-02-10 17:55 UTC, h31 commented on operations.js
> +        let user = users.users[Object.keys(users.users).find(user => users.users[user].login === decoded.login)]
Очень похожий код есть в соседнем файле

2022-02-10 17:55 UTC, h31 commented on operations.js
> +    } catch (err) {
Зачем нужен этот `catch`? Вроде в коде из `try` везде всё проверили и обработали. Плюс, какая ошибка может возникнуть, которая бы означала ошибку 403 (Forbidden)? Больше похоже на внутреннюю ошибку сервера (5xx).

2022-02-10 17:55 UTC, h31 commented on operations.js
> +    return new Promise((resolve, reject) => resolve(result));
Для чего здесь нужен `Promise`?

2022-02-21 16:52 UTC, k1unk commented on calc.md
> +GET /plus?o1={Value}&o2={Value}&authorization={Value}
Всё исправил

2022-03-15 06:47 UTC, h31 approved these changes
Всё хорошо, принимаю

2022-03-15 06:47 UTC, h31 commented on operations.js
> +       // let decoded = jwt_decode(req.headers.authorization);
Не забывайте удалять закомментированный код

2022-03-28 22:07 UTC, closed without merging