Lab 4_1. Астудина, Зайцева, Рубша, группа 3530901/80203
h31/NetworksLab2021 pull request #69
Opened 2022-02-06 17:32 UTC by astudina

2022-02-10 15:21 UTC, h31 requested changes

2022-02-10 15:21 UTC, h31 commented on lab4_1/API.md
> +      - JSON{"answer": "Failed"}
Непонятно, какую информацию несет этот JSON, помимо той, которую можно понять из status code. Почему это именно JSON? Какие из возможностей формата нужны в этом ответе?

2022-02-10 15:21 UTC, h31 commented on lab4_1/API.md
> +  {"cmd": "default"}
Зачем нужен параметр `cmd`, если по сути это три разных независимых запроса?

2022-02-10 15:21 UTC, h31 commented on lab4_1/converter.py
> +    def get_default_currency(self):
В Python не используют геттеры, если нужно добавить какую-то логику при выдаче значения, то применяют свойства (properties). В большинстве популярных языков ситуация такая же, исключение тут - Java, потому что в ней нет properties, и там всё ещё пишут геттеры.

2022-02-10 15:21 UTC, h31 commented on lab4_1/converter.py
> +            return {"list": "There is no connection with database",
Как клиентское приложение может понять, что сейчас находится в `"list"` - описание ошибки или корректное значение? Это явно две разные сущности, и храниться они должны в разных полях

2022-02-10 15:21 UTC, h31 commented on lab4_1/converter.py
> +                    "status_code": 500}
Мне нравится ваша идея разбить сервер на два файла - с сетевой частью и бизнес-логикой. Но сейчас разбиение неполное, как видим, сетевые вещи (status code, формирование ответа) просочились в файл с бизнес-логикой.

2022-02-10 15:21 UTC, h31 commented on lab4_1/converter.py
> +        if report is None:
Такой же код повторяется 3 раза в этом файле. Кажется, сократить код поможет использование исключений.

2022-02-10 15:21 UTC, h31 commented on lab4_1/converter.py
> +            currencies += currency + " "
Если это массив, зачем склеивать его в одну строку?

2022-02-10 15:21 UTC, h31 commented on lab4_1/converter.py
> +        return {"result": "{0:.4f}".format(result), "status_code": 200}
Зачем преобразовывать число в строку? Отображение - обычно задача клиента

2022-02-10 15:21 UTC, h31 commented on lab4_1/server.py
> +    if current_user.is_authenticated:
`logout_user()`?

2022-02-10 15:21 UTC, h31 commented on lab4_1/server.py
> +    logged_in_users = []
Зачем нужен этот список?

2022-02-10 15:21 UTC, h31 commented on lab4_1/server.py
> +    if not current_user.is_authenticated:
`@login_required`?

2022-02-10 15:21 UTC, h31 commented on lab4_1/server.py
> +            return {"answer": converter.get_default_currency()}, 200
Зачем здесь указывать `200`?

2022-02-10 15:21 UTC, h31 commented on lab4_1/server.py
> +def get_local_IP():
Зачем нужна эта функция? Есть ли другие способы, как можно слушать все интерфейсы, которые есть на компьютере?

2022-02-10 15:21 UTC, h31 commented on lab4_1/API.md
> +  {"cmd": "convert", "amount": "<amount>", "from": "<currency_ticker>", "to": "<currency_ticker>"}
Уверены, что параметры передаются по сети именно в таком виде (JSON)?

2022-02-10 15:21 UTC, h31 commented on lab4_1/client.py
> +            r = session.post("http://" + addr + "/" + route, args)
Не стоит автоматически приписывать `"http://"`, вдруг нам понадобится `"https://"`

2022-02-10 15:21 UTC, h31 commented on lab4_1/client.py
> +        return {"status_code": 503, "data": {"answer": "Server is disconnected"}}
Не понимаю, зачем вместо ответа сервера подставлять заглушку. Не проще ли изменить код, который вызывает эту функцию?

В целом, есть ощущение, что эта функция в текущем виде лишняя. Если разбить её на две, одну для GET, а другую для POST, то можно будет убрать `RequestType`. Обработчик 503 можно вынести из функции - вы в любом случае всегда завершаете приложение, когда возникает такая ошибка. Тогда, по сути, останется только формирование URL, которое как раз можно сделать в виде небольшой функции.

2022-02-10 15:21 UTC, h31 commented on lab4_1/client.py
> +    if re.fullmatch("(exit|default|ls|rate [a-zA-Z]+|convert ([0-9]+[.|])?[0-9]+( [a-zA-Z]+){2})", string):
Раз уж используете регулярки, посмотрите на группы и как с их помощью можно распарсить строку (вместо использования `split`)

2022-02-10 15:21 UTC, h31 commented on lab4_1/client.py
> +                        exit(r["data"]["answer"])
Эта строчка повторяется 6 раз в коде. Обработка исключений в целом повторяется несколько раз. Можно как-нибудь исправить это?

2022-02-10 15:21 UTC, h31 commented on lab4_1/client.py
> +        case 503:
В описании API ничего не говорится про ошибку 503

2022-02-11 19:06 UTC, astudina commented on lab4_1/server.py
> +    logged_in_users = []
Этот список используется в функции user_loader

2022-02-11 19:11 UTC, astudina commented on lab4_1/server.py
> +def get_local_IP():
Эта функция нужна для того, чтобы определить локальный IP адрес. При указании хоста можно просто поставить 0.0.0.0

2022-02-11 19:40 UTC, h31 commented on lab4_1/server.py
> +    logged_in_users = []
А для чего он нужен в этой функции?

2022-02-11 19:53 UTC, astudina commented on lab4_1/API.md
> +      - JSON{"answer": "Failed"}
Исправили этот и все последующие замечания

2022-03-15 06:29 UTC, h31 approved these changes

2022-03-15 06:30 UTC, closed without merging