Lab4
h31/NetworksLab2021 pull request #70
Opened 2022-02-07 09:17 UTC by Shadow-Haund

2022-02-10 15:43 UTC, h31 requested changes

2022-02-10 15:43 UTC, h31 commented on client.py
> +import threading
Лишний импорт

2022-02-10 15:43 UTC, h31 commented on client.py
> +regex = '[0-9]+[+\-\/*!^]{1}[0-9]*'
Лишняя переменная?

2022-02-10 15:43 UTC, h31 commented on client.py
> +            sending(hostF, json_to_send, "mul", user_name, password)
4 вызова, которые различаются лишь аргументом. Можно ли как-то сократить код?

2022-02-10 15:43 UTC, h31 commented on client.py
> +def sending(host, json, path, name, passw):
Обычно для имен методов/функций используют глаголы

2022-02-10 15:43 UTC, h31 commented on client.py
> +            response = requests.post(f"{hostS}/pow", json=json_to_send, auth=(user_name, password))
Две практически одинаковые ветви

2022-02-10 15:43 UTC, h31 commented on server.py
> +    posted = json.loads(request.body.getvalue().decode("utf-8"))
`request.json`?

2022-02-10 15:43 UTC, h31 commented on server.py
> +    posted["rez"] = rez
Если `rez` - это result, то лучше использовать другое сокращение (или вообще не сокращать)

2022-02-10 15:43 UTC, h31 commented on server.py
> +    print(rez)
Используйте логирование вместо `print`

2022-02-10 15:43 UTC, h31 commented on server.py
> +def multiplication():
4 практически одинаковых метода. Посмотрите, как Bottle.py помогает объединять похожие обработчики запросов

2022-02-10 15:43 UTC, h31 commented on server.py
> +@route('/slow/fact', method=['GET', 'POST'])
Если используете body запроса, то почему разрешаете GET-запросы?

2022-02-10 15:43 UTC, h31 commented on server.py
> +        number = number + 1
`number += 1`

2022-02-10 15:43 UTC, h31 commented on server.py
> +        dict_of_res[number-1] = {"status": "work is started"}
Где-то в программе используется эта константа - `"work is started"`? Отображается ли она пользователю? Есть ощущение, что для решение этой задачи достаточно хранить булеву переменную.

2022-02-10 15:43 UTC, h31 commented on server.py
> +    global number, dict_of_res
Ещё один метод, который практически дублирует предыдущий

2022-02-10 15:43 UTC, h31 commented on server.py
> +import json
Не хватает описания протокола обмена/API

2022-02-26 17:25 UTC, Shadow-Haund commented
Исправил все указанные ошибки

2022-02-26 17:25 UTC, closed without merging